# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-04 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_review', '0003_auto_20170603_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='developer',
            field=models.CharField(default='default', max_length=150, verbose_name='Developpeur'),
        ),
        migrations.AlterField(
            model_name='game',
            name='picture',
            field=models.ImageField(help_text="Pour garentir une experience utilisateur optimale, n'utilisez que des images .png", upload_to=b''),
        ),
    ]
