# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-04 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games_review', '0004_auto_20170604_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='developer',
        ),
    ]
